### ISSUE TITLE
Frequency Spectrum Plot Chapter 7 problems

### ISSUE THREAD

**Issue by ghost** [HackAudio/textbookcode#2]
Hey,

not sure if this is really a bug or intentional?

The [squareSynthesis function](https://github.com/HackAudio/textbookcode/blob/master/Ch_07/squareSynthesis.m) yields samples which are (sample_rate*seconds)+1 in length. 
Which works fine with the [frequency spectrum plot.](https://github.com/HackAudio/textbookcode/blob/master/Ch_07/plottf.m)

If I use a waveform that's exactly (sample_rate*seconds) in length, either nothing gets drawn (e.g. square) or wrongly drawn (e.g. sine).

I had to change `N = length(signal);` to `N = length(signal)+1;` to get it working with my exact samples.

All the best,
    Timo

**Comment by erictarrbelmont** [comment]
Thanks for letting me know. I will update the code in the repo to make it
work.
Eric

**Comment by erictarrbelmont** [comment]
The code has been updated each place the plottf function is used
